spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: budgeting
      username: root
      password: root123
      authentication-database: admin
      auto-index-creation: true

jwt:
  secret: "your-very-long-secret-key-at-least-32-characters-long!!"
  access-token-expiration: 900000 # 15 minutes in ms
  refresh-token-expiration: 2592000000 # 30 days in ms


cache:
  life: 60000 # 10 minutes in ms



server:
  address: 0.0.0.0
  port: 8080
