spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: budgeting
      username: root
      password: root123
      authentication-database: admin
      auto-index-creation: true
  output:
    ansi:
      enabled: ALWAYS

# 2. Custom log pattern for readability
# Format: [Time] [Level] [Thread] [Class] : Message
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"
  level:
    root: INFO
    com:
      budgeting:
        backend: DEBUG
    org:
      springframework:
        security: INFO
        data:
          mongodb: DEBUG

jwt:
  secret: "your-very-long-secret-key-at-least-32-characters-long!!"
  access-token-expiration: 900000 # 15 minutes in ms
  refresh-token-expiration: 2592000000 # 30 days in ms


cache:
  life: 60000 # 10 minutes in ms


server:
  address: 0.0.0.0
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /v3/api-docs

